export { HeroSection } from './HeroSection'
export { FeaturedProducts } from './FeaturedProducts'
export { PartnersSection } from './PartnersSection'
export { StatsSection } from './StatsSection'
export { TestimonialsSection } from './TestimonialsSection'
export { CTASection } from './CTASection'
